version: '3.9'
services:
  mqtt-broker-fleet:
    container_name: mqtt-broker-fleet
    image: eclipse-mosquitto:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
       - "1883:1883"
      #  - "9001:9001"
    volumes:
      - /Users/javideveloper/work/mqtt-vehicle-fleet-sensor-data/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /Users/javideveloper/work/mqtt-vehicle-fleet-sensor-data/mosquitto/data:/mosquitto/data
      - /Users/javideveloper/work/mqtt-vehicle-fleet-sensor-data/mosquitto/log:/mosquitto/log
    # security_opt:
      # - no-new-privileges:true

  mqtt-broker-vans:
    container_name: mqtt-broker-vans
    image: eclipse-mosquitto:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
       - "1884:1883"
    volumes:
      - /Users/javideveloper/work/mqtt-vehicle-fleet-sensor-data/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /Users/javideveloper/work/mqtt-vehicle-fleet-sensor-data/mosquitto/data:/mosquitto/data
      - /Users/javideveloper/work/mqtt-vehicle-fleet-sensor-data/mosquitto/log:/mosquitto/log
